#ifndef SERVO_CTRL_H
#define SERVO_CTRL_H

#include "pos_ctrl.h"
#include "params.h"

struct ServoUnit {
  ReferenceFrame servo_frame;
  Vec3D position;
};

struct EngineUnit {
  ReferenceFrame servo_frame;
  Vec3D position;
};

// Autogenerated function that does everything
void servo_move(PosOutputData input_waypoint);

#endif
